In [1]:
import pandas as pd
import numpy as np

In [5]:
black_friday=pd.read_csv('C:/Users/bharghava/Downloads/BlackFriday.csv')

In [6]:
black_friday.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [7]:
black_friday.describe()

User_ID    Occupation  Marital_Status  Product_Category_1  \
count  5.375770e+05  537577.00000   537577.000000       537577.000000   
mean   1.002992e+06       8.08271        0.408797            5.295546   
std    1.714393e+03       6.52412        0.491612            3.750701   
min    1.000001e+06       0.00000        0.000000            1.000000   
25%    1.001495e+06       2.00000        0.000000            1.000000   
50%    1.003031e+06       7.00000        0.000000            5.000000   
75%    1.004417e+06      14.00000        1.000000            8.000000   
max    1.006040e+06      20.00000        1.000000           18.000000   

       Product_Category_2  Product_Category_3       Purchase  
count       370591.000000       164278.000000  537577.000000  
mean             9.842144           12.669840    9333.859853  
std              5.087259            4.124341    4981.022133  
min              2.000000            3.000000     185.000000  
25%              5.000000            9.000000    5866.000000  
50%              9.000000           14.000000    8062.000000  
75%             15.000000           16.000000   12073.000000  
max             18.000000           18.000000   23961.000000

In [8]:
black_friday.isna().sum()# identifying null values

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            166986
Product_Category_3            373299
Purchase                           0
dtype: int64

In [9]:
black_friday.drop(["User_ID","Product_ID"], axis = 1, inplace = True)# Removing columns

In [10]:
black_friday.head()

Gender   Age  Occupation City_Category Stay_In_Current_City_Years  \
0      F  0-17          10             A                          2   
1      F  0-17          10             A                          2   
2      F  0-17          10             A                          2   
3      F  0-17          10             A                          2   
4      M   55+          16             C                         4+   

   Marital_Status  Product_Category_1  Product_Category_2  Product_Category_3  \
0               0                   3                 NaN                 NaN   
1               0                   1                 6.0                14.0   
2               0                  12                 NaN                 NaN   
3               0                  12                14.0                 NaN   
4               0                   8                 NaN                 NaN   

   Purchase  
0      8370  
1     15200  
2      1422  
3      1057  
4      7969

In [11]:
black_friday.isna().sum()

Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            166986
Product_Category_3            373299
Purchase                           0
dtype: int64

In [12]:
black_friday.Gender.unique() # to show the categeries

array(['F', 'M'], dtype=object)

In [13]:
black_friday.Gender.nunique()

2

In [24]:
black_friday.Age.unique() ## GOOD TO GO ##


array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [18]:
black_friday.Occupation.unique() ## IT IS DISCREATE DATA

array(['10', '16', '15', '7', '20', '9', '1', '12', '17', '0', '3', '4',
       '11', '8', '19', '2', '18', '5', '14', '13', '6'], dtype=object)

In [19]:
black_friday.Occupation=black_friday.Occupation.astype(str)


In [20]:
black_friday.City_Category.unique() ## ITS GOOD TO GO

array(['A', 'C', 'B'], dtype=object)

In [21]:
black_friday.Stay_In_Current_City_Years.unique() #good to go

array(['2', '4+', '3', '1', '0'], dtype=object)

In [22]:
black_friday.Marital_Status.unique() #good to go


array([0, 1], dtype=int64)

In [23]:
black_friday.Product_Category_1.unique() #good to go


array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9], dtype=int64)

In [29]:
black_friday.Product_Category_2.unique()


array([nan,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

In [26]:
black_friday.Product_Category_3.unique()


array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [27]:
black_friday.Product_Category_3.isnull().sum()

373299

In [28]:
black_friday.Product_Category_3.shape[0]# AFTER FILLING ZERO VALUES

537577

In [31]:
#proportion of null
black_friday.isnull().sum()/black_friday.shape[0]

Gender                        0.000000
Age                           0.000000
Occupation                    0.000000
City_Category                 0.000000
Stay_In_Current_City_Years    0.000000
Marital_Status                0.000000
Product_Category_1            0.000000
Product_Category_2            0.310627
Product_Category_3            0.694410
Purchase                      0.000000
dtype: float64

In [32]:
#to get no of unique values for all columns
for i in black_friday.columns:
    print (i, ':' , black_friday[i].nunique())
    

Gender : 2
Age : 7
Occupation : 21
City_Category : 3
Stay_In_Current_City_Years : 5
Marital_Status : 2
Product_Category_1 : 18
Product_Category_2 : 17
Product_Category_3 : 15
Purchase : 17959


In [33]:
black_friday.Product_Category_2.fillna("other",inplace = True)

In [34]:
black_friday.Product_Category_3.fillna("other",inplace = True)


In [35]:
#all columns are good to go
# all columns are discrete except y

black_friday_y = black_friday["Purchase"]

In [36]:
black_friday.drop("Purchase",axis = 1, inplace = True)

In [37]:
#x - Black_friday 
#y - Black_Friday_y

black_friday_x = pd.get_dummies(black_friday)

In [38]:
black_friday_x.columns


Index(['Marital_Status', 'Product_Category_1', 'Gender_F', 'Gender_M',
       'Age_0-17', 'Age_18-25', 'Age_26-35', 'Age_36-45', 'Age_46-50',
       'Age_51-55', 'Age_55+', 'Occupation_0', 'Occupation_1', 'Occupation_10',
       'Occupation_11', 'Occupation_12', 'Occupation_13', 'Occupation_14',
       'Occupation_15', 'Occupation_16', 'Occupation_17', 'Occupation_18',
       'Occupation_19', 'Occupation_2', 'Occupation_20', 'Occupation_3',
       'Occupation_4', 'Occupation_5', 'Occupation_6', 'Occupation_7',
       'Occupation_8', 'Occupation_9', 'City_Category_A', 'City_Category_B',
       'City_Category_C', 'Stay_In_Current_City_Years_0',
       'Stay_In_Current_City_Years_1', 'Stay_In_Current_City_Years_2',
       'Stay_In_Current_City_Years_3', 'Stay_In_Current_City_Years_4+',
       'Product_Category_2_2.0', 'Product_Category_2_3.0',
       'Product_Category_2_4.0', 'Product_Category_2_5.0',
       'Product_Category_2_6.0', 'Product_Category_2_7.0',
       'Product_Category_2_8.

In [40]:
#spiltting the data
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(black_friday_x,black_friday_y, test_size = 0.2)

In [41]:
#Gradient Boasting Regressor
from sklearn.ensemble import GradientBoostingRegressor

In [42]:
#model
GBR_model=GradientBoostingRegressor()


In [55]:
#model fitting
GBR_model.fit(X = train_x, y = train_y)


GradientBoostingRegressor()

In [54]:
print('to fit the GBR_Model',GBR_model.fit(X = train_x, y = train_y))

to fit the GBR_Model GradientBoostingRegressor()


In [45]:
#accuracy
GBR_model.score(test_x,test_y)

0.6399576995850905

In [46]:
#for cross validation result 
from sklearn.model_selection import cross_val_score

In [48]:
scores = cross_val_score(GBR_model,black_friday_x, black_friday_y, cv = 5)

In [51]:
print('the values of 5 scores',scores)

the values of 5 scores [0.63793903 0.64029919 0.64003727 0.64148514 0.63784499]


In [56]:
np.mean(scores)

0.6395211247788751

In [57]:
print('the mean value of scores is',np.mean(scores))

the mean value of scores is 0.6395211247788751


In [58]:
np.std(scores)

0.0014171534229765108

In [59]:
print('the STD value of scores is',np.std(scores))

the STD value of scores is 0.0014171534229765108
